### ISSUE TITLE
Missing voices

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/onikakushi#12]
Voice is missing for [this line](https://github.com/higurashi-mod/onikakushi/blob/5cced1dea710333a3157163ad97a0663d442ff14/Update/onik_009.txt#L515-L518).

Voice for [this line](https://github.com/higurashi-mod/onikakushi/blob/5cced1dea710333a3157163ad97a0663d442ff14/Update/onik_009.txt#L693-L695) doesn't work even though it is in the script (file s19/02/500200780 does not exist)

[This line](https://github.com/higurashi-mod/onikakushi/blob/5cced1dea710333a3157163ad97a0663d442ff14/Update/onik_009.txt#L2493) uses a wrong voice file, the same file is used [here](https://github.com/higurashi-mod/onikakushi/blob/5cced1dea710333a3157163ad97a0663d442ff14/Update/onik_009.txt#L2563) as well which is correct.

Thanks for working on this patch!

**Comment by ItaloKnox** [comment]
You are correct in the three points. Since I don't have the right files and I've been away from the recent developments, I think Cnnctr might know what is going on.

**Comment by ItaloKnox** [comment]
Okay, fixed everything. Just download the master file or replace onik_009.txt and everything will be fixed.

**Comment by enumag** [comment]
Thanks! :-)
