### ISSUE TITLE
Wrong line

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/onikakushi#15]
[This line](https://github.com/higurashi-mod/onikakushi/blob/fb64713485702b14c5dd5be63fc1a6e6ba73ef9e/Update/onik_009_02.txt#L1124) is wrong - it was the other way around. The one who hesitated was Tomitake and Takano finished the sentence for him. At least from the voices, not sure what the original japanese text says.

If you're going to fix it, keep in mind that Keiichi doesn't know Takano's name yet at this point.

**Comment by ItaloKnox** [comment]
I recommend forking the repository, fixing the script and then making a pull request. Since that's not a bug, there is not much I can do.
