### ISSUE TITLE
Voice file used twice

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/onikakushi#25]
Voice file s01/02/120200256 is used [here](https://github.com/higurashi-mod/onikakushi/blob/bb5ad280b4fc9fad96188f49072576edb79f5410/Update/onik_014.txt#L3866) and then again few lines later [here](https://github.com/higurashi-mod/onikakushi/blob/bb5ad280b4fc9fad96188f49072576edb79f5410/Update/onik_014.txt#L3979). I believe the first usage to be wrong. I think few lines before the wrong usage the text and voice are out-of-sync because some voice file actualy covered two lines of text.

**Comment by ItaloKnox** [comment]
Thanks for reporting this one. Already fixed it, that was probably a copypaste that went wrong.

**Comment by enumag** [comment]
Actually you did not fix it. Not file ...255 is used twice.

**Comment by ItaloKnox** [comment]
So the problem is actually bigger than it looks, because the dialog matched. Give me a minute to check the script again.

**Comment by enumag** [comment]
Yup, that's what I've talked about above - the voice and text is out of sync for few lines.

**Comment by ItaloKnox** [comment]
Some lines were actually out of sync, as you said. I found a match for a specific set of sounds (120200251~120200256), but I don't know if there are more. Can you check it again?

**Comment by enumag** [comment]
There is one more error - s01/02/120200257 is used twice.

**Comment by ItaloKnox** [comment]
Thanks, that was actually a misplaced line. They look pretty similar in japanese, so maybe that was the source of all confusion.

**Comment by enumag** [comment]
Are you sure there is no voice file for that line? The dialog feels like there should be one.

**Comment by ItaloKnox** [comment]
It does but the line before that actually covers the entire block (check [here](https://github.com/higurashi-mod/onikakushi/blob/master/Update/onik_014.txt#L3865-L3884)). That might be a problem in sync with the text, since the timers plus clicks might be off. Only way to "fix" that is to replace the audio with three split audios or sync the script with the audio.

**Comment by enumag** [comment]
I checked it again in the game directly, you're correct. I think it's ok to leave it be. Thank you for your patience. :-)
