### ISSUE TITLE
Question: What is the difference of this version with the original steam?

### ISSUE THREAD

**Issue by jezenielzapanta** [higurashi-mod/onikakushi#33]
Aside from chapter 1, are there any changed scenes from this patch?

**Comment by ItaloKnox** [comment]
I think there's one or two scenes changed aside from that. Minor changes, not even close to what happened in chapter 1.
I don't remember which scenes, though.

**Comment by enumag** [comment]
@ItaloKnox What is changed in chapter 1?

**Comment by ItaloKnox** [comment]
[That scene with Mion and Keiichi](https://github.com/higurashi-mod/onikakushi#known-issues) about his morning vigor or something like that. That scene was impossible to have voices without changing the content to match the PS3 version.

**Comment by jezenielzapanta** [comment]
Thanks for the quick reply. +1
