### ISSUE TITLE
Steam update

### ISSUE THREAD

**Issue by waffleman1230** [higurashi-mod/onikakushi#35]
A steam update for Hig just came out that screws up this mod. Can u fix it?

**Comment by ItaloKnox** [comment]
Can you explain what is happening? My game is updated and the patch works fine.

Try deleting the entire CompiledScrips folder contents (>> SteamApps\common\Higurashi When They Cry\HigurashiEp01_Data\StreamingAssets\CompiledScripts), maybe that will fix your problem. I don't know how to help if you don't provide any details.
