### ISSUE TITLE
Sound mismatch near the beginning

### ISSUE THREAD

**Issue by Norgus** [higurashi-mod/onikakushi#37]
Sorry if this isn't the right way to report this, but I'm not really used to using github.

In the file
onik_002.txt
line 1637 plays a sound file "s19/04/990400046" which covers not only this bit of text, but the following one too.
However, on the following bit of text, the next sound file is played on line 1644 - "s19/04/990400047" and does not match the text (and indeed is repeated a few lines of game text later)

I don't know how best to fix this.
1) The audio file ending 46 could be split into two and assigned to each half of the gametext
or
2) The two prompts worth of gametext could be merged into one to match the sound

I suspect that 2 is easier but I haven't tried it yet.

**Comment by ItaloKnox** [comment]
Thanks for reporting this. I merged both lines, but both ways are easy to do.
Do you have a save file close to this scene? I would like to see if it was really fixed.

Download the master file if you want the new script. Also don't forget to reset the compiled folders.

**Comment by Norgus** [comment]
Thanks for the fast response!
I have a feeling I came across something else earlier too but forgot about it.
I was planning to play through the whole thing, so I'll try to remember to make notes when I notice stuff.

If I find more than a few, I'll work out the forking and pull-requesting stuff.

**Comment by ItaloKnox** [comment]
Sure, thanks for the help. You might notice some cases like this one, unfortunately many of them are unavoidable if you are a slow reader or playing on auto.
Take note of the cases that completely breaks the flow of the game, I'll take care of them (or you can pull request them, that helps a lot!).
