### ISSUE TITLE
Text boxes patch?

### ISSUE THREAD

**Issue by JaxxBlaxx** [higurashi-mod/onikakushi#5]
Not an issue, but would it be possible to add a patch to add text boxes like the PS2 version of Higurashi instead of the text covering the whole screen?

**Comment by ItaloKnox** [comment]
Probably yes but that also implies several changes in text behaviour. Unless Doddler makes it really easy somehow (auto-cutting lines and all that stuff to prevent lines "bleeding"), I don't there will be someone willing to review and edit every line of text.
